package:
  name: anaconda-clean
  version: "1.1.1"

source:
  git_rev: v1.1.1
  git_url: https://github.com/ContinuumIO/anaconda-clean

build:
  entry_points:
    - clean = anaconda_clean:main

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - anaconda_clean

about:
  home: https://github.com/ContinuumIO/anaconda-clean
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Delete Anaconda configuration files
  dev_url: https://github.com/ContinuumIO/anaconda-clean
